export const ACTIONS = {
  PLANETS_LOADED: 'PLANETS_LOADED',
  PEOPLE_LOADED: 'PEOPLE_LOADED',
  CHANGED_ACTIVE_ITEM: 'CHANGED_ACTIVE_ITEM',
  REQUEST_DATA: 'REQUEST_DATA',
  DATA_LOADED: 'DATA_LOADED',
};
